name: Deploy Frontend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "VITE_API_URL_DEVELOPMENT=${{ secrets.VITE_API_URL_DEVELOPMENT }}" >> .env
          echo "VITE_API_URL_PRODUCTION=${{ secrets.VITE_API_URL_PRODUCTION }}" >> .env
          echo "VITE_STRIPE_PUBLIC_API_KEY=${{ secrets.VITE_STRIPE_PUBLIC_API_KEY }}" >> .env
          echo "VITE_STRIPE_PRIVATE_API_KEY=${{ secrets.VITE_STRIPE_PRIVATE_API_KEY }}" >> .env
          echo "VITE_DEV_MODE=${{ secrets.VITE_DEV_MODE }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
