// Camada de compatibilidade lucide-react -> @phosphor-icons/react.
// Reexporta sob os nomes que os componentes do app já importam, para que a
// migração seja só uma troca da origem do import, sem tocar em JSX.
// Peso default "regular" (traço fino, igual ao visual do lucide); "fill" só
// deve ser usado manualmente em ícone de IA/copiloto e estado ativo,
// conforme design_handoff_trackerr/README.md.
export {
  Warning as AlertTriangle,
  WarningCircle as AlertCircle,
  Pulse as Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowsDownUp as ArrowUpDown,
  CurrencyBtc as Bitcoin,
  Brain,
  Briefcase,
  SealCheck as BadgeCheck,
  ChartBar as BarChart3,
  Bell,
  Robot as Bot,
  Building,
  Buildings as Building2,
  Calculator,
  Calendar,
  Clock,
  Calendar as CalendarIcon,
  Camera,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  CurrencyCircleDollar as CircleDollarSign,
  Question as CircleHelp,
  Coins,
  Cookie,
  CreditCard,
  Crown,
  Cpu,
  Diamond,
  Dot,
  Download,
  CurrencyDollar as DollarSign,
  PencilSimple as Edit,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  FileXls as FileSpreadsheet,
  FileMagnifyingGlass as FileSearch,
  DotsSixVertical as GripVertical,
  Globe,
  GitDiff as GitCompare,
  Hexagon,
  Info,
  Key as KeyRound,
  Bank as Landmark,
  Stack as Layers,
  CircleNotch as Loader,
  CircleNotch as Loader2,
  SignOut as LogOut,
  Envelope as Mail,
  ChatCircle as MessageCircle,
  ChatCircle as MessageSquare,
  Moon,
  DotsThree as MoreHorizontal,
  SidebarSimple as PanelLeft,
  Pencil,
  ChartPie as PieChart,
  PiggyBank,
  Plus,
  QrCode,
  ArrowClockwise as RefreshCw,
  ArrowCounterClockwise as RefreshCcw,
  ArrowCounterClockwise as RotateCcw,
  Receipt,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Shield,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShieldSlash as ShieldOff,
  Shuffle,
  Sparkle as Sparkles,
  Star,
  Sun,
  Target,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  LinkBreak as Unlink,
  UploadSimple as Upload,
  User,
  UserCircle as User2,
  Users,
  Wallet,
  X,
  XCircle,
  Lightning as Zap,
} from '@phosphor-icons/react';

// Additional aliases for missing icons
export {Clock as CalendarClock, Question as HelpCircle} from '@phosphor-icons/react';

// Type export for compatibility with lucide-react
export type {Icon as LucideIcon} from '@phosphor-icons/react';
