// Camada de compatibilidade lucide-react -> @phosphor-icons/react.
// Reexporta sob os nomes que os componentes do app já importam, para que a
// migração seja só uma troca da origem do import, sem tocar em JSX.
// Peso default "regular" (traço fino, igual ao visual do lucide); "fill" só
// deve ser usado manualmente em ícone de IA/copiloto e estado ativo,
// conforme design_handoff_trackerr/README.md.
export {
  Warning as AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowsDownUp as ArrowUpDown,
  SealCheck as BadgeCheck,
  ChartBar as BarChart3,
  Bell,
  Robot as Bot,
  Building,
  Buildings as Building2,
  Calculator,
  Calendar,
  Calendar as CalendarIcon,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  CurrencyCircleDollar as CircleDollarSign,
  Question as CircleHelp,
  Coins,
  Cookie,
  Crown,
  Dot,
  Download,
  PencilSimple as Edit,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  DotsSixVertical as GripVertical,
  Info,
  Bank as Landmark,
  CircleNotch as Loader,
  CircleNotch as Loader2,
  Envelope as Mail,
  ChatCircle as MessageSquare,
  Moon,
  DotsThree as MoreHorizontal,
  SidebarSimple as PanelLeft,
  Pencil,
  PiggyBank,
  Plus,
  ArrowClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Shield,
  ShieldCheck,
  Sparkle as Sparkles,
  Star,
  Sun,
  Trash as Trash2,
  TrendUp as TrendingUp,
  UploadSimple as Upload,
  User,
  UserCircle as User2,
  Users,
  Wallet,
  X,
  Lightning as Zap,
} from '@phosphor-icons/react';
